service: bicycle-licence-ledger-consumer
plugins:
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters
provider:
  name: aws
  runtime: java8
  region: eu-west-1
  memorySize: 256mb
  timeout: 300

package:
  artifact: target/bicycle-licence-ledger-consumer-1.0.0-SNAPSHOT.jar

custom:
  enquiryTableName: licence

functions:
  bicycleLicenceLedgerConsumer:
    handler: uk.gov.dvla.poc.bicycle.BicycleLicenceLedgerConsumer
    events:
      - stream:
          type: kinesis
          batchSize: 1
          startingPosition: TRIM_HORIZON
          maximumRetryAttempts: 10
          enabled: true
          arn:
            Fn::GetAtt:
              - bicycleLicenceLedgerStream
              - Arn
    iamRoleStatementsName: bicycle-licence-ledger-consumer-lambda-role-${self:provider.stage}
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "kinesis:GetRecords"
          - "kinesis:GetShardIterator"
          - "kinesis:DescribeStream"
          - "kinesis:ListStreams"
          - "kinesis:PutRecord"
          - "kinesis:PutRecords"
        Resource:
         Fn::GetAtt:
          - bicycleLicenceLedgerStream
          - Arn
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
          - "dynamodb:UpdateItem"
          - "dynamodb:GetItem"
          - "dynamodb:DeleteItem"
        Resource: "arn:aws:dynamodb:${self:provider.region}:#{AWS::AccountId}:table/${self:custom.enquiryTableName}-${self:provider.stage}"
      - Effect: "Allow"
        Action:
          - "xray:PutTraceSegments"
          - "xray:PutTelemetryRecords"
        Resource: "*" # Restrict resource to minimum required
resources:
  Resources:
    bicycleLicenceLedgerStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: bicycle-licence-ledger-event-stream
        ShardCount: 1
    BicycleLicenceLedgerConsumerLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        TracingConfig:
          Mode: "Active"
    bicycleLicenceLedgerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.enquiryTableName}-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: S
        KeySchema:
          - AttributeName: "id"
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST


